# Ejercicio Notebook 7
## Diferencia entre *matrix* y *array* en Numpy

Las matrices (matrix) en Numpy deben ser de 2 dimensiones, a diferencia de los arreglos (arrays) que pueden ser multi-dimensionales (1D, 2D, 3D,...,ND). Los objetos de matriz son una subclase de ndarray, por lo que heredan todos los atributos y métodos de ndarrays.

La principal ventaja de una matriz en Numpy es: *es relativamente simple hacer la operación de multiplicación*. Por ejemplo, a y b son dos matrices, entonces a*b es una matriz producto.

In [1]:
import numpy as np

a=np.mat('4 3; 2 1')
b=np.mat('1 2; 3 4')

print("Matriz a:",a)
print("Matriz b:",b)
c=a*b
print("Matriz c:",c)

Matriz a: [[4 3]
 [2 1]]
Matriz b: [[1 2]
 [3 4]]
Matriz c: [[13 20]
 [ 5  8]]


Lo contrario es que en un arreglo de numpy las operaciones se realizan elemento por elemento, por lo que en el siguente ejemplo la operación del arreglo c*d será diferente al resultado de a*b aunque tengan los mismos valores en las mismas posiciones:

In [2]:
c=np.array([[4, 3], [2, 1]])
d=np.array([[1, 2], [3, 4]])
print("Matriz c:",c)
print("Matriz d:",d)
e=c*d
print("Matriz e:",e)

Matriz c: [[4 3]
 [2 1]]
Matriz d: [[1 2]
 [3 4]]
Matriz e: [[4 6]
 [6 4]]


Para multiplicar un arreglo como matrices se utiliza el comando dot de Numpy

In [3]:
f=np.dot(c,d)
print("Matriz f:",f)

Matriz f: [[13 20]
 [ 5  8]]


Como a es una matriz, ** devuelve el producto de la matriz a*a.

In [4]:
print(a)
print(a**2)

[[4 3]
 [2 1]]
[[22 15]
 [10  7]]


Como c es una array, ** devuelve una array con cada componente en forma de elemento cuadrado.

In [5]:
print(c)
print(c**2)

[[4 3]
 [2 1]]
[[16  9]
 [ 4  1]]


Existen otras diferencias técnicas entre los objetos de matriz y las arreglos (arrays) (que tienen que ver con np.ravel, selección de elementos y comportamiento de secuencia).

La principal ventaja de las matrices numpy es que son más generales que las matrices bidimensionales. ¿Qué pasa cuando quieres una matriz tridimensional? Entonces tienes que usar un ndarray, no un objeto de matriz. Por lo tanto, aprender a usar objetos matriciales es más trabajo, tiene que aprender las operaciones de objetos matriciales y las operaciones ndarray.

Escribir un programa que use matrices y matrices hace que su vida sea difícil porque tiene que hacer un seguimiento de qué tipo de objeto son sus variables, para que la multiplicación no devuelva algo que no espera.

Por el contrario, si solo utiliza ndarrays, puede hacer todo lo que pueden hacer los objetos de la matriz, y más, excepto con funciones/notaciones ligeramente diferentes.

## array o matrix, ¿cuál debo usar?

Históricamente, NumPy ha proporcionado un tipo de matriz especial, np.matrix, que como dijimos anteriormente es una subclase de ndarray que hace que las operaciones binarias sean operaciones de álgebra lineal. Puede verlo usado en algún código existente en lugar de np.array. Entonces, ¿cuál usar?

***Usar matrix.***

NumPy contiene tanto una clase de matriz como una clase de matriz. La clase de array está destinada a ser un arrego n-dimensional de propósito general para muchos tipos de computación numérica, mientras que la matrix está destinada a facilitar específicamente los cálculos de álgebra lineal. En la práctica, solo hay un puñado de diferencias clave entre los dos.

**Operadores * y @, funciones punto () y multiplicar ():**

Para un array, `` * `` significa multiplicación por elementos, mientras que `` @ `` significa multiplicación de matrices; tienen funciones asociadas multiply () y dot (). (Antes de Python 3.5, @ no existía y había que usar dot () para la multiplicación de matrices).

Para la matrix, `` * `` significa multiplicación de la matriz, y para la multiplicación por elementos, uno tiene que usar la función multiplicar ().

**Manejo de vectores (matrices unidimensionales)**

Para la array, las formas vectoriales 1xN, Nx1 y N son todas cosas diferentes. Operaciones como A [:, 1] devuelven un arreglo unidimensional de forma N, no una matriz bidimensional de forma Nx1. La transposición en una matriz unidimensional no hace nada.

Para matrix, las matrices unidimensionales siempre se convierten en matrices 1xN o Nx1 (vectores de fila o columna). A [:, 1] devuelve una matriz bidimensional de forma Nx1.

**Manejo de arrays de dimensiones superiores (ndim> 2)**

Los objetos de array pueden tener un número de dimensiones> 2;

Los objetos de matrix siempre tienen exactamente dos dimensiones.

**Atributos de conveniencia**

El array tiene un atributo .T, que devuelve la transposición de los datos.

Matrix también tiene atributos .H, .I y .A, que devuelven la transposición conjugada, inversa y asarray () de la matriz, respectivamente.

**Constructor de conveniencia**

El constructor de arrays toma secuencias de Python (anidadas) como inicializadores. Como en, matriz ([[1,2,3], [4,5,6]]).

El constructor de matrix también toma un inicializador de cadena conveniente. Como en la matriz ("[1 2 3; 4 5 6]").

## Pros y Contras de usar arrays o matrix
### Array

:) La multiplicación por elementos es fácil: A * B.

:( Debe recordar que la multiplicación de matrices tiene su propio operador, @.

:) Puede tratar matrices unidimensionales como vectores de fila o columna. A @ v trata a v como un vector de columna, mientras que v @ A trata a v como un vector de fila. Esto puede ahorrarle tener que escribir muchas transposiciones.

:) La matriz es el tipo NumPy "predeterminado", por lo que obtiene la mayor cantidad de pruebas y es el tipo con más probabilidades de ser devuelto por un código de terceros que usa NumPy.

:) Se siente cómodo manejando datos de cualquier número de dimensiones.

:) Más cerca en semántica del álgebra tensorial, si está familiarizado con eso.

:) Todas las operaciones (*, /, +, - etc.) son por elementos.

:( Las matrices dispersas de scipy.sparse no interactúan tan bien con las matrices.

### Matrix

: \\ El comportamiento es más parecido al de las matrices MATLAB.

<:( Máximo de dos dimensiones. Para contener datos tridimensionales, necesita una matriz o quizás una lista de matriz de Python.

<:( Mínimo de dos dimensiones. No puede tener vectores. Deben convertirse en matrices de una sola columna o de una sola fila.

<:( Dado que la matriz es la predeterminada en NumPy, algunas funciones pueden devolver una matriz incluso si les da una matriz como argumento. Esto no debería suceder con las funciones de NumPy (si lo hace, es un error), pero se basa en código de terceros on NumPy puede no respetar la conservación de tipos como lo hace NumPy.

:) A * B es una multiplicación de matrices, por lo que se ve como si lo escribiera en álgebra lineal (para Python> = 3.5, las matrices simples tienen la misma conveniencia con el operador @).

<:( La multiplicación por elementos requiere llamar a una función, multiplicar (A, B).

<:( El uso de la sobrecarga de operadores es un poco ilógico: * no funciona en términos de elementos, pero / lo hace.

La interacción con scipy.sparse es un poco más limpia.

## Conclusión

Por lo tanto, el **array** es mucho más recomendable de usar. De hecho, tenemos la intención de desaprobar la **matrix** eventualmente.

# Ejercicios notebook 8

<img src="https://rebornhugo.github.io/assets/images/post_images/%E5%BC%BA%E5%8C%96%E5%AD%A6%E4%B9%A02/bellman%20equation2.PNG">

* n = número de estados del sistema.
* V(s) = vector que representa el valor esperado para cierto estado
* R = recompensa inmediata percibida por el agente al salir de cierto estado.(vector)
* P = matriz de transicion de la cadena de Markov sub-yacente.(matriz)
* γ = factor de descuento de recompensas futuras(escalar)

Calcular V(s) para el siguiente sistema aplicando la ecuación de bellman de manera vectorizada.

In [6]:
V = np.array([0,0,0]) # valor inicial de V(s)
R = np.array([10,2,5]) # vector de recompensas
P = np.array([[0.5,0.25,0.25],
              [0.2,0.40,0.40],
              [0.80,0.10,0.10]])  # matriz de transición
gamma = 0.99

V = R + (P*gamma)
print(V)

[[10.495   2.2475  5.2475]
 [10.198   2.396   5.396 ]
 [10.792   2.099   5.099 ]]


**Ejercicio aplicado en DS**
Se tiene una red neuronal sencilla(y simplificada) como la de la siguiente imagen:
<img src="https://www.oreilly.com/library/view/practical-convolutional-neural/9781788392303/assets/246151fb-7893-448d-b9bb-7a87b387a24b.png">

Donde:
* INPUT LAYER: un vector X de tamaño = 2 que representa los datos de entrada
* HIDDEN_LAYER :capa oculta con 2 neuronas definidas por los vectores:
    * HL1 = [0.25,0.37]
    * HL2 = [-8,14]
* OUTPUT_LAYER = capa de salida definida por el vector [4,9]

Crear una funcion neural_network(X) para calcular:
* Calcule la salida de cada neurona en la capa intermedia aplicada a la capa de entrada.
* Use el resultado del paso anterior como entrada para la neurona en la capa de salida

Utilizando multiplicación de matrices se debe calcular para cada fila de la matriz de entrada X el valor de las neuronas de la capa intermedia, esto producirá una nueva matriz con el mismo número de filas que X y 2 columnas(1 para cada neurona) , a  los valores de esta matriz se les debe aplicar la función "sigmoid"(descrita a continuación) para limitarlos al intervalo de 0 a 1, esto produce una matriz del mismo tamaño pero con valores entre 0 a 1, esta matriz se multiplica matricialmente por la matriz que representa los pesos de la capa de salida  y este proceso produce un nuevo tensor al cual se debe aplicar nuevamente la función sigmoid. El resultado debe ser un tensor con el mismo número de filas que la matriz X y una sola columna(una predicción para cada fila de X.

<img src="https://cdn-images-1.medium.com/max/1600/1*Xu7B5y9gp0iL5ooBj7LtWw.png">

In [7]:
# Aplicar la red neuronal sobre los siguientes datos X

X1 = np.array([0.50,0.72])
X2 = np.array([-4,7])
X3 = np.zeros_like(X2)
X4 = np.ones_like(X1)
X5 = np.random.randn(X1.shape[0])

HL1 = np.array([0.25,0.37])
HL2 = np.array([-8,14])
OUTPUT_LAYER = np.array([4,9])

def sigmoid(x): #convertir los valores de x al rango de 0 a 1
    return 1/(1+np.exp(-x))

def neural_network(X):
    HL1_dot = np.matmul(X,HL1)
    HL2_dot = np.matmul(X,HL2)
    
    #HIDDEN_LAYER
    HL = np.array([HL1_dot,HL2_dot])
    
    HL = sigmoid(HL)
    
    T = np.matmul(HL, OUTPUT_LAYER)
    
    T = sigmoid(T)
    #OUTPUT_LAYER
    return T

print("X1:",neural_network(X1), 
      "X2:",neural_network(X2), 
      "X3:",neural_network(X3), 
      "X4:",neural_network(X4), 
      "X5:",neural_network(X5))

X1: 0.999988416671698 X2: 0.9999955493876428 X3: 0.998498817743263 X4: 0.9999906359245414 X5: 0.8448022502952601


### Ejercicio 

Implementar en una funcion neural_network(X) la red neuronal definida por la siguiente arquitectura:

<img src="http://i.imgur.com/UNlffE1.png">

Podemos validar si fue correctamente implementada si usamos como entrada el vector x=[1,1] . Debemos obtener el resultado mostrado en la imagen.

Una vez tenemos la implementacion correcta, cambiar la funcion de activacion de la capa de salida por la funcion de activacion ReLu(https://en.wikipedia.org/wiki/Rectifier_(neural_networks)):

<img src="https://cdn-images-1.medium.com/max/1600/1*DfMRHwxY1gyyDmrIAd-gjQ.png">

Luego evaluar la red neuronal sobre la matriz de datos X(de manera vectorizada):

In [8]:
# Aplicar la red neuronal sobre los siguientes datos X
# Usando la función de activación sigmoid
HL = np.array([[0.712,0.355,0.268],
              [0.112,0.855,0.468]])

OL  = np.array([[0.116],
                [0.329],
                [0.708]])

def sigmoid(x): #convertir los valores de x al rango de 0 a 1
    return 1/(1+np.exp(-x))

def neural_network_s(X):
    HL_M = sigmoid(np.matmul(X,HL))
    #print(HL_M)
    #TARGET
    TG = np.matmul(HL_M, OL)
    #print(TG)
    TG = sigmoid(TG)
    return TG

X1 = np.array([1,1])
print("X:",neural_network_s(X1))

X: [0.69269553]


In [9]:
X = np.array([
    [0.1,2],
    [0.3,0.45],
    [5,9],
    [12,6],
    [7,5],
    [0.3,0.8],
    [12,5],
    [100,200],
    [7,8],
    [300,1500]])
print(neural_network_s(X))

[[0.70244573]
 [0.66259284]
 [0.75933678]
 [0.75973948]
 [0.75802295]
 [0.6739704 ]
 [0.75954693]
 [0.76005845]
 [0.75952743]
 [0.76005845]]


In [10]:
# Aplicar la red neuronal sobre los siguientes datos X
# Usando la función e activación ReLU
HL = np.array([[0.712,0.355,0.268],
              [0.112,0.855,0.468]])

OL  = np.array([[0.116],
                [0.329],
                [0.708]])

def reLU(x):
    out = np.maximum(x, 0)
    return out

def neural_network_r(X):
    HL_M = reLU(np.matmul(X,HL))
    #print(HL_M)

    #TARGET
    TG = np.matmul(HL_M, OL)

    TG = reLU(TG)
    return TG

X1 = np.array([1,1])
print("X:",neural_network_r(X1))

X: [1.014762]


In [11]:
X = np.array([
    [0.1,2],
    [0.3,0.45],
    [5,9],
    [12,6],
    [7,5],
    [0.3,0.8],
    [12,5],
    [100,200],
    [7,8],
    [300,1500]])
print(neural_network_r(X))

[[1.2901751e+00]
 [3.9827325e-01]
 [7.5763340e+00]
 [8.4233580e+00]
 [5.8520720e+00]
 [6.1724410e-01]
 [7.7977270e+00]
 [1.6403930e+02]
 [7.7289650e+00]
 [1.0551858e+03]]
